spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8
    read-only: false

  mvc:
    hiddenmethod:
      filter:
        enabled=true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5